#!/bin/bash
echo " FOLLOW THE INSTRUCTIONS CAREFULLY " lolcat
echo ""
echo ""
echo " 1 AUTOMATICALLY GO TO TELEGRAM BOT PAGE "
echo ""
echo " 2 CLICK START BUTTON ON TELEGRAM BOT PAGE "
echo ""
echo " 3 THEN BACK TO TERMUX AND TYPE python main.py +(county code and mobile number)"
echo ""
echo " wait 20 second " 
echo ""
