#!/bin/bash
#code by tech cochi
clear
bash logo
about
sleep 20
xdg-open https://t.me/Litecoin_click_bot?start=aH4M
sleep 20
echo " wait 20 second "
pip install -r requirements.txt
unzip telethon.zip
rm -rf telethon.zip
clear
bash logo
echo ""
echo ""
echo ""
ls

