#!/bin/bash
# code recorded by tech cochi
# new update 
clear
printf "\e[93m   ____ ______   ______ _____ ___  \e[0m\e[1;91m   __  __ ___ _   _ _____ ____ \e[0m\n"  
printf "\e[93m  / ___|  _ \ \ / /  _ \_   _/ _ \ \e[0m\e[1;91m  |  \/  |_ _| \ | | ____|  _ \ \e[0m\n" 
printf "\e[93m | |   | |_) \ V /| |_) || || | | | \e[0m\e[1;91m | |\/| || ||  \| |  _| | |_) | \e[0m\n"
printf "\e[93m | |___|  _ < | | |  __/ | || |_| | \e[0m\e[1;91m | |  | || || |\  | |___|  _ < \e[0m\n" 
printf "\e[93m  \____|_| \_\|_| |_|    |_| \___/ \e[0m\e[1;91m  |_|  |_|___|_| \_|_____|_| \_\ \e[0m\n"
printf "\e[92m CODE BY TECH COCHI  V² \e[0m\n"                                                           
printf " \n"
