import os
import sys
import time
os.system("pkg install figlet")
os.system("clear")
os.system("figlet Hocker-X")
print("Enter your name")
name = input() 
time.sleep(2)
print("====================================================")
print("----------------Ddos attack started!----------------")
print("====================================================\n")
time.sleep(3)
print("====================================================")
print(":::::::::::::::::IP adress tracked!:::::::::::::::::")
print("====================================================\n")
time.sleep(3)
print("====================================================")
print("~~~~~~~~~~~~~~Bypassing all security~~~~~~~~~~~~~~~~")
print("====================================================\n")
time.sleep(5)
print("Congratulations,",name,"! You have successfully hacked:")
time.sleep(3)
os.system("figlet NASA")
time.sleep(2)
os.system("exit")