#! /data/data/com.termux/files/usr/bin/bash
        R='\033[1;31m'
        G='\033[1;32m'
        Y='\033[1;33m'
        B='\033[1;34m'
        M='\033[1;35m'
        C='\033[1;36m'
        W='\033[0m'
echo
echo $(clear)
echo
echo -e "$C Disfruta instalando las versiones\n de metasploit que quieras"
echo
sleep 3
echo $(clear)
echo
echo
echo -e "$C Instalando requisitos"
echo
sleep 3

pkg update && pkg upgrade -y
pkg install wget curl php -y
pkg install python2 -y




echo
echo
echo
sleep 3


rm -rf $HOME/msf/msf
rm -rf $HOME/CesarHackGray


	echo $(clear)
	
cd $HOME/msf


	echo $(wget https://raw.githubusercontent.com/Cesar-Hack-Gray/release-download/master/msf)

	echo $(clear)


mv $HOME/msf/msf $PREFIX/bin


chmod 777 $PREFIX/bin/msf

rm -rf $HOME/CesarHackGray
rm -rf $HOME/msf

	echo $(clear)


	echo
	echo
	echo
	echo
	echo
	echo

echo -e "$C Ejecuta como $G  msf "

	echo
	echo
	echo
	echo
	echo
	echo
	echo




