#!/bin/bash
#Colors
white="\033[1;37m"
grey="\033[0;37m"
purple="\033[0;35m"
red="\033[1;31m"
green="\033[1;32m"
yellow="\033[1;33m"
Purple="\033[0;35m"
Cyan="\033[0;36m"
Cafe="\033[0;33m"
Fiuscha="\033[0;35m"
blue="\033[1;34m"
nc="\e[0m"

echo ""
banner () {
echo -e $'\033[0;35m  _      __ ____ ___    ____ _____ ___    _  __   \e[0m'
echo -e $'\033[0;35m | | /| / // __// _ )  / __// ___// _ |  / |/ /   \e[0m'
echo -e $'\033[0;35m | |/ |/ // _/ / _  | _\ \ / /__ / __ | /    /    \e[0m'
echo -e $'\033[0;35m |__/|__//___//____/ /___/ \___//_/ |_|/_/|_/     \e[0m'

}
banner
echo ""
printf "\033[0;35m Coded by Farhan | Nethunter \e[0m\n"
printf "\033[1;37m ----------------------------------------------------\e[0m\n"
echo -e $'\e[1;37m\e[0m\e[1;33m AUTHOR  : DARKNET HAXOR \e[0m'
echo -e $'\e[1;37m\e[0m\e[1;33m YOUTUBE : YOUTUBE.COM/DARKNETHAXOR \e[0m'
echo -e $'\e[1;37m\e[0m\e[1;33m PAGE    : FACEBOOK.COM/DARKNETHAXOR \e[0m'
echo -e $'\e[1;37m\e[0m\e[1;33m GITHUB  : GITHUB.COM/DARKNETHAXOR \e[0m'
echo -e $'\e[1;32m ----------------------------------------------------\e[0m'

