
### <?php
echo $red."[!] warning !!!".$t;
echo $kuning."[-] ini adalah program ilegal".$t;
echo $kuning."[-] resiko sepenuhnya di tanggung pengguna".$t.$ijo.$t;
$stat_ads=true;

$ads= $putih.'[*] '.$ijo.'subcribe youtube sungging '.$t.$putih."[÷]    official channel    [÷]".$t.$ijo."[-] adi bordir ".$putih."| atau |".$ijo." sungging [-]".$t; 

$msgtoto = "[!] Subscribe Youtube adi bordir dan Sungging".$t.$ijo."[•••••] sekilas info [••••••]";

$msgyd = "[!] ganguan pada server jangan panik ini tidak lama";
$yd_stat = true;
$vip1= false;
//$weblock =["Imam Almasyah Risanzani",];
$ydblock = ["Imam Almasyah Risanzani",];
$we_stat = true;

$msgwe = 
"[#] msg by => adidoank ".$t.
"[!] info pendaftaran member di tutup".$t.
"[-] vefun telah menghentikan layanan aplikasinya".$t.
"[-] terimakasih telah menggunakan tools ini".$t.
"[-] salam gretongers para tuyul indo".$t;
$donasi=true;
$msgveeu = "[!] update skrip veeu".$t."[•] git clone https://github.com/adidoank/veeu";

$data= ['H84391','C19302',
'adi bordir','L41023','adi doank','I46346','ssunggingg',
 'Adi Digitizer','Dzi','semua andinya','sungging','asep kanceuh','putripesek','nubie305','ateng','Bal Lack','Maulana Setiawan','suga zora','Thauvan GT','yassar sha\'id shafi\'i','Moezza 01','စုံလင်သော အလ','hasan coc','Pro Master','hasan abut','gan bro','Yudi Pratmaja','Gembel Elite','imel telu','SkaLova','Badrun','Nhóc Con Sr','Delwin Yoanes',
'Beuti Lavea','MasterCraft Vn','Ari Sandi','I love Cartoon','Kaboom','Robert Simangunsong','Mohamad Husn',
'Lucy Thien','Adi Trader Demo','Mif Takhul','Feyy','I Dewa Gede Superatikadewa','Wendik','Qohwah',
'Asmuri Aas','Goril Aas','Wili Aas','Gery Aas',
'Redi Aas','Fenjul','Sabar Ajah','Dewi Tati','Fenjul',
'Hasan','Yuli Iyul','Yun Yuyun','Davis','Novita',
'$ FARHAN Z $','Muhammad Nandars','Muh Nandar',
'Dep Bell','Adis Ahmat','Wali Roy','Roy Purba',
'Acik Mall','Salim Aas','Bela Aas','Andrie',
'Andriean','Andriesun','Acik Mall','Salim Aas',
'Bela Aas','Rujana Bakong','Farid Mohamed','Dewi Aas',
'Dila Aas','Bili Aas','Flybird Yuan','Teri Aas',
'Den Aas','Amin Aas','Wulan Aas','Hasan Aas','Yusri','Fachrul Ejp','ajit vepal','Agus Riyadi',
'Agus Riyadi Riyadi','Richard Steven Try',
'Yoviar Pauzi','Ayesha Advocate',
//vipm
'HARIS Denzlot','Raihan Chainago','Bejo Jo206','Bejo Rusak','Jordan Donathan','Bejo Mace','Jojo Vake','Deaso Bejo','Lungkik Cuiru','Riyan Kartika','Lusto Rusak','Jorsn Rusak','Jordwun jerdin','Curit Astjx','Hais Suis',
//mpiv
'Gem Bel','Hati Yang Terluka','Umi Kholiifah',
'Aditiya Sarofi Putra','NOOB GAMING','phim lẻ','Jordwun lrus','gan bro','Gan Bro','bot siji',
'bot loro','bot telu','yu di','aryant259','Janandito W',
'arifin','Noob Player','yoyomamam90@gmail.com','Andi Aas','elang aja','Muhammad Paijo','Sutejo','Siti Azizah','Dian Kartika','Budi Aas','Raby Aas',
'Wendy Aas','Rani Aas','Lê Hoàng','Rere Aas','Rony Aas',
'Riki Aas','Junaidi Abdulah','Tidak Dikenal','Agung Nugraha','SobLok DanSka VoltHz','Afil X-friends Discography Hitam-Putih','Aan TheRG','Davin Hardit',
'robert simangunsong','Restu OnGame','santa lidwyna tarigan','NEWBIE BERKELAS','Bambang Setiawan',
'Mr. Benk','Yafia Ah','Yafiah Tri Ramdani wijaya',
'nayz stone','Myvi Com','Seda Coeg','Wayan','Kiki Albani','Kresna Rizkie','itel meh','gretonger Tool','bball','Remsha Rajpout','Khalifi','Hasan Ahmmad YK','Ahmad_alfian','bondex pay','Mona Xperia',
'BangGenzzot Gaming','Addinansah Azmil Hidayat','Elza Mila','astrajingga18','Astrajingga','Chiko Andrea',
'Thoriq','Agus Saepuloh','Muhammad Feb','SWITCHCASE CHANNEL','djindonesia34@gmail.com','Hole Jewelry','Fina','Pooja Lalwani','Mobi legend','Agung Prakoso','manol watu','Nandi Wardana','Golek Duwit','kintel gedi','Haris Setyawan',
'switchcase advertising','mody prasetya','Hasan Bgp','Reno Aas','Rexy Aas','Boby Aas','Reno Aas','Reva Aas','Riky Aas','Reff Aas','Rix Aas','Rahmy Aas','Bay Aas','Caca Aas','Yuki Aas','Rini Aas','Gege Aas','Adi Aas','Wewe Aas','Golek Duwit','Dapi Aas','Sapi Aas','Rehu Aas','Rehi Aas','Witi Aas','Akbar Cara','Akbar Oite','Akbar Akb','Akbar Albert','Loge Cara','Alis Cara','Rema Cara','Forta Cara','Fewe Cara',
'Wani Aas','Rara Aas','Fewe Cara','arif','Rizal Rapz','Woodpecker Woody','Febryansyah','Babang Ary','Mila Milenia','Ary Ary','Jon Son','Tukafi Acucre',
'Josie','Davita Brietta','Charisse Cariotta','Bilkis','Sundari','Reksi Aas','Adex Aas','Iyul Aas','Rexy Aas','Tery Aas','Ulex Aas','Sule Aas','Rex Aas','Fiikhozii JR Fiikhozii JR','Danu Antwo','ibnuramadhan','Ahmad Fathoni','Jeff Buizon','ayr official','Febryan','Febryan','Ika Sinta','Ujenk The Restovers','NoobSec ID','Berita Terkini','Paypal Hunter','Curhat Mas','kobe sacac','Yakub Setiawan','Zal Case',
 'Sofhia Harlan','Januar Krist','Benac','akmal miftah','Ainur Rofik','Gatanzi','Makarti','rafif dwi','Muhammad Dim','Aris Ryan','Karin Dyah','Haris Reno','Riri Melati','Lee Huy','Andi Setia','Afifah Dwi','Yuni Sara','Lisa Gea','Rangga Saputra','Sutrisno Abdi','Putra Maulana','SKIPPER FAME','Erik Irawan','ZiBn','Marcel Roni','Sherly Cantika','Suci Lestari','Novri Haris','Rico Pangabean','shandhe kalla','ragad jaya',
'inpinix inpo','RONY Taylor','Farel Pratama','Azzahra Diana','Calista Arsy','Revano Aditya','Monic Ika','Gibran Alvin','Ilyasa Syauqy Hummam','Lukman Hakim','ilyasa syauqy','adham.farros22@gmail.com','Mustofa Aji','layla.axis125@gmail.com','zilonggg124@gmail.com','fanny.victory22@gmail.com','gusion.dagger121@gmail.com','lance.hitz120@gmail.com','lolita.axis23@gmail.com','balmon.botak19@gmail.com','lesley.lele99@gmail.com','lapulupa22@gmail.com',
'triệu linh','Giew Giew','Jancog','Ok Oc','wayan dhanayasa','E27692','P71770','B91100','91truonggiabao@gmail.com','Hendria Jaya Saputra','Nana Dalam','Ahmad Fauzy ','Fauzy Gaming','Mas T','Azmil Limza','Anh Minh','Toni Utama','Mona Soulmatre','Dollar Gratis','Mas Yanto','Mas Ariel','Sobar','Eca','Dodi','Bally','Dozer','Yudi Pratmaja','Mas Yuyut','Siti Amani','H52687','Y81206','Z95400','P96029','N91967','H70527','S48399','Firman Syah Rizal',
 'Ipman Kirishima I','Z95125','Ipman Kirishima II','Ipman Kirishima III','Ipman Kirishima IV','Ipman Airlangga I','Ipman Airlangga II','Ipman Airlangga III','Shinobara Arata','Unlock NF','N90740','fasya ramada','Aris Wijaya','Yosa Zainul Hasan','Muhammad Haris','Shoniaa Nisa','Junron Lasno','Yadi Kice','Gersik Turen','Bulan Warni','Jorik Jerok','Kusno Kerdil','Haris Denslo','Nita Farida','Vira Aml','Gilang Sarwah','Cira Harti','Lusandar Jangkar','Herman Luis','Reno Sunandar','Shoniaa Nisa',
 'Robby Ari','Kuroiwa Arata','Ipman Airlangga VI','Ipman Airlangga VII','Ipman Airlangga VIII','Ipman Airlangga IX','Genji Maeda','Ipman Airlangga XI','Yery','Mery','Dego','Bima','Lithonia','Huy Le','Vira Aml','Abdissabiq Haqi','Ceramah Manfaat','AGOEZ MARIYANTO','Ka Sabelas','Saidina Ali','Cimeng Blues1','Ade ZJ','Cimeng Blues2','Zein Azka Muhammad','Emai','Bally','Banjar','Tia','Budi','Gita',
'Gan Bro','Gan Bro','Gan Bro','Gan Bro','Gan Bro','Gan Bro','Azy Ciel','Pelangi','Hasan','Dewi','Dojer','Tika','Ema','Liman','Gerry Gerry','Mukhalim Khalim','Lukman Nulhakim','Azka Abdul','Anu Kahiji','Anu Kadua','Anu Katilu','Anu Kaopat','Anu Kalima','Anu Kagenep','Anu Katujuh','Anu Kasalapan','Anu Kadalapan','Lutpi Abdul','Sipa Nurul','Lukman Bungbulang','Cimeng blues','Ka Sapuluh','prima putra','Amir Rais','Bunga Indah','Charly Daniel','Dina Khairunnisa','Evan Gani','Uning Garong','Ryan Akbar',
'Wulan Diyana','Asyadi Wirna','Nofrizon Fajrin','nofrizon fajrin','Ghoni Saputra','Hantu Uka','hayati moet','Cundru Nayla','Andi Ygtersakititukkeduakalinya','Luki Yuno','Ruben Firmansyah','faisal aliansyah','Kino Yuno','Susu Kntl','Hack Game Mobile','ReyBeth Tino','Ridwan Bernanti','Mr X','Chaca Ismatullah','Ronnachai','Nature Forget','liyhumhay00@gmail.com','nuyul reward','co phaichac','Emas Selawati','andi s.n','JembutSutra','Raden Panji Tri Wahyudi','Duy Thu','anosystem25@gmail.com','H73490',
 'Richard Kennedy','Sare','Dila','Tiara','Ema','Sandi','Duda','Tari','Ema','Liman','ғᴜɴ 3x','Anas Ali Tegar','Daku Bhai','Tatang Charles','Dea Pitaloka','Ex Treme','Khusnan','Fatwa Gaming','Sandi Main','Eko Prasdeatre','Heri Deafour','Jono Deafivi','Bejo Deasix','Hari Deaseven','Sugik Deaeigh','Tio','Tukang Nuyul','Hariyantoa','Владислав Белов','Hariantob','Hariantoc','Agus Safirudin','Sandi Pratama','Sandi','Rere','Sarwo','Bahlul','Tikno','Carry Chandra','Sidiq Pangestu','Adi Bordir','Jennifer Ballard',
'Jono Khairurin','Andri','Badriya','Bambang','Baidi','Beby','Bejo','Fa_dhil7','Oje Ardi','Risnado','fadlan tuwaffa','Shela Samsung',
/*
 'N58140','O10784','J15232','V27584','M94778','V98855','H44906','U61395',
 */
 'Donny Suhendra','Wildan Zaki','Kaum Fals','Sule Sutisna',"Mayar Hutang",'Terry Soja','Rani Floren','K4note Vz','Zevorz Qone','Teh Ci','ARI PRADANA','Adit','Andika Boy','Mad Dog','Suya Siip','Fenjul','Durah','Buana','Ema','Sarry','Buana','Mahdi','Sarry','Gethux\'k Rassa Apha\'sadja','SunDul U','Luthfi Ahmad','Reyzall','Reyzall','Reyzall','Isra Novita','didik cahyono','didik cahyono','didik cahyono','didik cahyono','didik cahyono','ayra khoirunnisa','Nandang Triswanto','LUTHFI ZXC','Adelia Aurelia','semak233',
'Irawati','norie espino','Reyzall','Reyzall','Reyzall','Reyzall','Reyzall','Reyzall','Putra','Charis','Muhammad Fauzan','Gvz Dua','Kanda Kuan','rama ccc','Fachrul Rozzy','Yafi\'ah Tri Ramdani Wijaya','Febriyan Muhammad','Brian','Ciplay Nub','Guancok','Guabruel','Silvia','Muhammad Rafli','creator pro','Maman Hilman','Rara Puspita II',' 　 ꧾꧾ','Rahayu Sarah','Febri','Namaku Panjang','Namaku Panjang','Anfort Sadase','Gian Puqi','Reyzall','Kus Irawan','AGila','Reyzall','Feni Wati','Ghani Ahmad','Reyzall','Hani Dyan','Reyzall','Indra Karim','Reyzall','Reyzall','Jeni Ira','Reyzall','Rizki Dian Ananda','Reyzall','Wolu Pitu','Karim Ahmad','Lena Ayu','Mikazuki','Muh Ryan','hanz moo',
'Mario Banu','Nana Eti','Obi Raihan','Reyzall','U Chinx','Reyzal','Reyzall','Rikudo Minggu','Rey Zall','Ryzal','Fachroni Sofyan Bachrin','VIP Generation [OFFICIAL]','Roni Bachrin','esta rosa','Garmer Max 18','ꦑꦺꦴꦲꦶꦫꦸꦭ꧀','Zainal','rizkirmdn','Man Jada','Cply 12','Ciplay 13','Y81914','cekcok aje','Sarif Hidayat',
'Putra Lyn','Peni Silvi','Qiqi Indra','Rara Riri','Desty Anggrayuni','Steven Junior','Tina Janah','Rizki Amanda','Jajang','Nurjaman','Ainx','Dwi Bagus','Rafif Setiawan','santy fibrianty','Johnson Amatir','Putra Gans','Thio Aditya','ilhamm akbr','Ayase Chihaya','Ilyas Ar Rafii','Tutorial IT','Della Bore','Apip Hidayat','Rezky Afr','Mio Oi','Nuyu Siji','sungging','Nuyul Loro','Nuyul Telu','Nuyul Papat','Nuyul Limaa','Cah SAMDIK','Nuuyul Enem','Mas Boot','Nuyul Pitu','Nuyul Wolu','Nuyul Sanga','Nuyuul Seepuluh','Nuyull Sewelas','Nuyul Rolas','Nuyul Telulas','Nuyul Patbelas','Nuyul Limalas','Mas Agung','Mas Galu','Mas Adit','Mas Niko','Mas Genji','Mahmudin BJ','Belajar Bareng','Nuyul Kedua','Mas Jonek','Mas Ariel','Mas Maeli',
'uyu','Dara Mancyku','Chris Roy','Daniel Wen','Elma Suhaira','Dora Seki','Mark Webber','Fioren Mark','Ronggo Waluyo','Prowu Uty','Jun Mus','Enggar Dwi','Abdi Daus','Imansyah Fir','Stephen Inurae','Johan Doms','Reni Abggarein','Saya Mawar','Tito Pahlevi','Irma Rochimah','Goapri Ajeu','Cualo Buam','Paguao Laue','cdroid3','SoniaaDwiyuliaa','Iyhah Romay','Sindharu','Richard Kennedy','Richard The Lionheart','Cply 04','Sky Nouses',
'Ciplay07 Pitu','Ciplay08 08','Cply 10','UtonMU','Anime OP','أنجس موسلين','Muhammad Farhan','Yt GM review','Dhiloet 1603','GROUNDS GAMING','Jeff Buizon','M Koi','  ꧾꧾ','Fazar Dany','Zonkid',
'Pok Ame Ame','Didik Cahyono','Akazaki Kun','Afiq','John Strazza','Mas Yusuf','Mas Aryok','Sifak Slegean','Afil Slegean','cdroid3','Jupri Semprol','Mas Zilong','Mas Johnson','Mas Mansur','SoniaaDwiyuliaa',
'Iyhah Romay','Ar Ya','Malam Crot','Sky Nouses','hasan','Anime OP','أنجس موسلين','Muhammad Farhan','Yt GM review','Dhiloet 1603','Tahu Gejrot','GROUNDS GAMING','M Koi','  ꧾꧾ','miikann19@gmail.com',
'Fazar Dany','Zonkid','Puput','Didik Cahyono','Akazaki Kun','Afiq','Mbk Gisel','ronalddolss@gmail.com','Rio Syaputra','Mas Ipul','Mas Yoki','Mas Karem','Puput','ilham okta pradinata','Karden Kuri','Mas Antoni','Mas Butok','Mas Bagio','Mas Cungkring','Mas Jaeni','ツAverrose','Bang Sat','Wildan Pramana','ZONK ID','Manamanaman Manamanamamama','Diamond Black','Harris Arifin','Questions','Hendrayusril','Sakata','Adi Purna','Mas Naryo','Modalhp Dapat Uang',
'Aldo Adniar','Mas Dafa','Mas Lut','Mas Husein','Mas Kholek','han raihan','lorius• нαηz','raihan choirul insan','sempako pak','Anzany Demo','CumaMusik YT','Mitra Aryo','Muzakir Glp','Mifta Stretford\'End','Bobbie Ali',
'Haykal Herna','ifan firdiyan','Rofi Rofik','Anyar Meren','Channel Tai','Siti Ruroh','Andi Dista','Rahmad Tullah','Tania Ros','Egya Safwy','Ferdian','Adinda','ghoni3 saputra3','Diki Clor','RaffiNi Assasin',
'Ai','Hafida Mutia','Andree','Lina','Adib Ardianto','Sabrina Julianna','Jeck Monday','Kimsbo','Levin Tauris','sempako pak','Jennifer Currie','Fahleri','Chaniago','Siti Nurhafifah','Dini Afzar','Joy Rafel','Rafael','Dafi','Herry','Sari','Baidah','Carly','Surti','Tarjo','Ayu','Dewi','Cicha','Ryan',
'Putra','Laura','Arya Dipake','ivan rizky','AQifatul Fatim','Mas Jimin','Neng Ayu','bastards in silence silence','Neng Dita','Neng Gisel','Neng Fafa','anak malam','09 Nam','Aminah Zainuddin',
'Whing','bemzmancung0@gmail.com','Mas Afgan','Mas Jembot','Mas Harjo','vias utami','Mas Waluyo','Mas Anjir','pink queen','Jamal Kurnia','kupak pak3','Ilderson Chacon','Al Hilmi',
'Abdul M','alit huuh','dewab259@gmail.com','alit krisharjoko','kupak pak4','Hilmi Septian','Ladut Singht','Kawasaki Gto','Stance Nation','Moto Rolla','Tips and Tri','kupakpak5@gmail.com','Irfan Febrian','Andy Slengkak','Mas Bayu','Mas Anga','Mas Jihan','Marvin Musa','Mas Dito','Mas Cici','kupak pak6','D2!! Air Drops !!','VL Channel','Mas Gading','Mas Likan','Dex Fina','Mas Parmen','WolfDust HD','Mas Bowo','kupakpak7@gmail.com','Agung Al Qorni','lazada Com','Lazada Com','Meike','Rizki Yuraa','Risna Ana','AL HiLmi','Al Hilmi','Amelia Sunjaya Tjhin','Ja Bok','Ajudan Ban','No Vel','Ahmad Habib Al Hilmi','Iksa','Korina','Iskandar','Kurniasi',
'Georgio','Shantia','Faras','Saraswati','Ilham','Rafi farrel','Alfino Chees','AK 13','Ex Vide17','Wahyuantor13y Rizyi','Telek Nules',
'Indra Prasetyo',
'Wahyuanto16 Rizi','Wahyuanto17 Rizkie','Riz18 Wah','19riz Wahyu','Rexy maulana','Abim Joss','Sukinah','Ajudan Letoy','ajudansepeda100@gmail.com','ajudangila100@gmail.com','Shivhari Mainali','Fitri Anda','Comot Tukul','Shivhari Mainali','Fitri Anda','gamer\' z','Verlie','Eddye Law','Mawardi Jani','Kunyuk Monyet','Muhammad Agung','Dus Tha','Geloy Madeso','Quriy Kiyam','Lesley Loveu','Viona Salome','ibuachyati001@gmail.com','Lumar Tree','Tolee','Ajoo','Parlin','Rizky Wahyuanto','Ambo Imma','Anto Suhan','Sobri Uy','Bang Andi','Bang Ateng','Bang Kanceuh','Bang Ari','Muhammad Andhika Prasetya','davidkriswanto8619@gmail.com','Räjå Rómãdhøñý','Creator Pro','Epe Fi Taa','Fandy Ahmad','Dima Kolikov','kollpolretro@gmail.com','Oscar Magdonalf','Indra Sopian','Rafael Wintoro','Thonz Mulyana','Tolee','Ajoo','Parlin','Rudi','Nisa','Istar','Rozali','Fatonah','Zayn Zyan','Cetar','Badai','ajudanmotor100@gmail.com',
'Iklan Admob','Erik Sudarto','Alex','Dicky Perdana','Rendy','Ajudanwsn','Wahyuantor','Ajudankjy','Ajudanzcimugg','Wahyuantordua','Ajudanmnbi','Wahyuantortiga','Ajudanxelenzv','Ajudan Letoy','Wahyuantorempat','Bambang Setiawan','Linagendt','Wahyuantorlima','Ajudanvoguhe','Wahyuantorenam','Ajudanautypx','Ajundanando','Wahyuantortujuh','Ajudanbxs','Ajudanjfg','Wahyuantordelapan','Ajudanz','Wahyuantorsembilan','Yogi Raja','Jre Quack','dol25sokid88@gmail.com','Jaud Blaut','Sriayu Lestari','Ayu Sri','Indra Sopian','Rafael Wintoro',
'Thonz Mulyana','Iklan Admob','Erik Sudarto','Alex','Dicky Perdana','Rendy','Yogi Raja','Jre Quack','dol25sokid88@gmail.com','Jaud Blaut','Sriayu Lestari','Ayu Sri','Indra Sopian','Mustafa Gomaa','V Raizo Bin Blekicot','Wahyuantorsebelas','Wahyuantortigabelas','Wahyuantorempatbelas','Wahyuantorduabelas','Wahyuantorlimabelas','Boby Bo','Emyx Xiaomi','EX-CORE DEV','Eto Rahmat','Wahyu Eko','Ronny Syawa Al-Fauzany','Toyol Bos','Majid Noujie','kampang kampang1','Λςιɖ βυrη','Eldi Memet','giga koli','Vinh Lê','koli koli','Saya Sendiri','jusu parti','Andika Sulta','Ajudan Sendal','Ajudanbecak','ajudansendal100@gmail.com','ajudanbecak100@gmail.com','Ajudannoefuibq','Ajudandgelzi','Ajudanytvybx','Ajudanyscfva','Ajudanzyg',
'Lampu Merah','demonz666 last','dlast demonz','Imtitsal Hibatulloh','Agung Arya pratama','Chii Wen','LangBoncezz Boncezz','Mark Engelo','Adrian Tantowi','Fitra Bayu','Sukma Febriani','Ambo Imbi','Adrian Tantowi J','Free Vps Android','Phi Lix','Your Reg','Dova Giovano','agil kholis','XkazerukaX M','Maxcyb','asudoweh@gmail.com','sean segundo','Kirisaki Mirai','addekasur@gmail.com','Romario Show','Anggi','hoyolkop@gmail.com','Kanekusan Salibra','Rooby',
'goloj567@gmail.com','Kolo Pol','Cewek Main M','Rony Handry Mustofa','Mohamad pratama Mukti','HjPro FD','Kenzie','Arrel Peter','Fahmi Arifan','Ahmad Farochi','Tempoyak Gaming','Fahmi A.','uang dollar','Tania Ayu','zainal ilmi',
'Achmad Hasan Ramdhanie','Andri Ada Mangopo','Jenderal Bulo','Revaldo Nadio','Khusnil Ibad','roobyjarwo','adi doank','TanpaNama',
'Bayu Arya','feli
','Buyut Berbunga','Goyeng Asoy Asoy','Hilda','Omae Adn','Ai yohan',
'Run','Hunter Killer','Cornellio Dommey Dhoe','Ucok Oo','seftyan poerboyo','Agent Red','Tuan Kiet','Luthfy Kurnia Fadly','fallen savage','Jaya Wijaya','Norah C Gaming','Akbar Riski','The Clash','opslank12@gmail.com','Arya Ahmed',

'Reza Miftahul Anas','S S','wahyu innoes','Saiful Imam','kamaluddin muktar','Blackberry Z3','Novri Wendra','Dudi Sopyan','Intan 2017','Sirin MSC','DeathSilver I Servidores configurados y plugins!','Felipe Batista','Dewo Bayu','Felipe Batista','Felipe Batista',

'Pedri Antonito','Juan Yeecero','Pepe Tervero','Ramananta ','hacker s','Agus','Fahmy','fahmy amirudin','Eva Nurjannah','Bang Ands','Siska Kelvin','Perfect Kill','Pak Cik','michkaelkelvin@gmail.com','pak dee',

'heru w','Ahmad fachrudin','ulauli341@gmail.com','Syubbanul Musthofa','Apa Adanya','Ped Rebellious Squad','Rizky Ok','Fakih Ade','sinyoayu3@gmail.com','Feren Reza Reynaldo','Uzonedancok Asu','Khaerul','Hadi','princealbert294@gmail.com','Anwar',

'Fil Pol','Adim Trimo','Bhongol Crew','sururi Amin','chrisna bayu','Riki Sudarso15','Iqbal A.R','mino lagi','Gb Jkt','Koko Kurnia','jajaxok@gmai','Game Master','Zaky Maulana','Echa Moedji','Лэвиш Подольський',

'Ahmad Fachrudin','Panyun','maseco aja','Indah','Speedek','Gigi22','Agung Lesmanàa','Agus Ryanto','NNchannel Gaming','Enjoy Bambela','Enjay Mangkir','ahmad hamdy','Ramiro Minucci','Brandon Sanchez de García','Agus Asep',

'fakunsatu1@gmail.com','Guruh Nugroho','chris alfonso','Kalil Bernardo Andrada','pali luuluu','Muhammad Ayash','Ijo Lan','Rivaldy','Peter Natanael','Bob 92','Kori','Livermore Endless','DiKdik Kra','Galih Nuryono','Faizal Abidin',

'Remkidz','Febri','Ramadhan Firman','Fathol','andi.dika3460@gmail.com','Black Bolt','rezza curut46','Nicholas Parasian','SetiaAja','Igg Igg','Sukri Sabar','11 11','nggak JELAS','Erlangga Cliquerz','The Dion','Ucoq','Ucoq','Kiki Jarrodt','Rhavael Sumilat','M Lan','Rokim Wae','Anu','re za','Dyland Dildo','Bayu Apriyanto','Apung Arniadi Gunawan','kevin Soetri','ariba Game','Smart B0y','rislan3yakin@gmail.com','Pahadangan Hajanah','Patrick Mark','Wewei','Koko','Adi Rano lee','hasanudin','Anu Vps','Kopay Hideng','Ardiansyah Dalimunthe','Feri Setiawan','ESA BVC','David Dtse','omujundwrt@gmail.com','Dede Brayen','muhammad fik','sumaj500@gma','Iantiger92','Fears Nothing','Christian Tindoc','Fear he who ','R AN','Ari Setiabud','pencinta gamers','Soni Herman','Jupe Suca','fadhlyiqbal3@gmail.com','jokokolo76@gmail.com','Lap','Agni Yusuf','faisal04','Rizki Wardana','Yusfachlevi ','Yusfachlevi Reza R','faisal Alamsyah','arief nabhan','Arsya Zain','Fahbel','Dede Lesmana','Seiya','Quanqi','danu wiranugraha','Dwi Vankurie',
'Andika','Leek Tutoriais','Febri Listio','Faisal Alamsyahh','Faisal Alamsyah','internet news','Gilang\'198 \'','Skyline Missing','Jeff Mamun','Ahmad Fahreji','Akun Veeu2','Naska Ridho','Rizal Anugrah','Lucas Martin Biasi','Den Mas Bagus','New No Name','Akunku Kehack','Aksanjr Jr','YT Zam Lagu','Guris Ceng','Toni Lamon','Lintang Aca','Kharismadani gdz','Guyskid Hastawangi','Bagi ga Gamin','Ifah Latifah','Joyo Bendot','asep mulyana','Bang Slow','aris mulyana','Rima Susanti','Angga15','Excel Pradna','Faiz Yahya','teman Explorer','Dimas Homies','Kapten Vunkky','Upin Ipin','Asep Kurniadi','DANIEL ANCHU','Muhammad Syarif','Putri Andini','RfiRsky12','Ainul Rhamadhan','Rudy Bae','Matrix Mango','Cholid Achmad','mobilelegend87 baru','Arispubji','Amana Putri','Aldi Yahya','aldi yahya','Bong Parl','Deedee','Miftah Fauzy','phellnandhol official','Andy SkyLine','Km Krisnuartha','akun baru','Bakul Gambar','Experimental Music','ПРИКОЛ ГИФ','Cerme Raya','Cahyo Bhudhy','Annas Arya','dhimas aulia','sandika uchiha','Rakha Nurraffa','xangiox','Cokerzz Gamingzz','Rockman Sullivanz','Agus Setiawan','onyip gedang',
'yogi pratama','Ankaira Pram','Jihan Xfrendz','Purnama Agung','CHRLT Channel','serenamonic1','Lintang Nurul Kh','bento yalle','Faris Hizba Hisbullah','nyoman nyoman','Begger Crypto','Mode Pesawat','Syahrul Taufik','amar arwed','daniel roserbut','Chandra Adi M','Septian Apriansyah (septianaps)','giw pisan','YASER MEDIA','Mirjan Hidayat','ramadoni','Jav Gaming','Rangga Kusum','poli robot','Dicka Setiawan','Rifkii Setiawann','Rifki Setiawan','Ilham Maulana Sukma','Azis Herjunot','ajudantuyul100@gmail.com','Rahul Khan','Fathor Hoir','taofiksar03@gmail.com','Hafri yanto','Rian Enx',
//vip
"W96630",
//adidonk 
'serenamonic1','Adam Ersanur','Wind Ci','TANPA BATAS','Alifian Dzaki','LK tv','ilham maulana','Duki Duketo','Danang Mahmud','Alto Hadi Lukita Jaya','Adam Ersanur',
'Putry We','Mhmd Jejen','ssophan channel','Ferdy Ndest','Nanang Hermansyah','Dede Mukhtar','Lastlah Anjing','Fauji Ikhwana','Red Roseate','Red Roseate','faisal ztm','mobile lengendary',
//sungging
'Safitri ,','ANAK TUTORIAL','Azis Herjuno','Eka Jaya','Aji Maulana','Klasynky Gege','DEni Muach','Mustofa Agil','Viki Waluyo','TMCyber ArmyTM','Ferdy Rizaldi','Anun YK Ina','Len','Bilal Maulana','Maman','Angga Sena Casandra','paulsculd678@gmail.com','ANGGI','Muhammad Ikbal','Jrock Star','Muhammad Irman Raya','Purwono','Ikbal Kepalasuku Ujungpanrang','baca plus','Lucky Lucky','Zedrik Bam','Rahma Only\'For One\'Heart','Muhammad Zafran Alfariq','Agara Net',
//input
 'APRI YANTO','Aditya Ramad','Anun Dwi Yulianto','G62546','E27692',
'Veranda vee','Miyako Titin','Gugung Jagi','G12717','Sinyorie Enorie','Ventura','Sry Jayaa','Kontoru Sama','Kwarasan Kenapa','Fanss Milyha','game gue','Cemul','Milyha Dipa','Parzy Leor','Alifian Dzaki','Meka Alfin Permana','Tukang Copas','adieb nur hafidz','Milytha Pabji','Ridhos Hago','Ridho YK','Nogotirto YK','tuyul baru1','Thursina Anna','Dja Rot','Dini Suswanti','宙宜尺尹','Krisna Ilham','Yogi Martha','Kristiana Honnie pilsa','N\'chev Jepank','asepairil22@gmail.com','Muh Zuhdi','Kang Roki','Fachrurodzii','Moch Tham','Dìmoka Deo','Faris HariSandy','Muh Zuhdi','Rizaldi Alfian','Roselle Santos','yusufsapta31@gmail.com','Tajul Arifin','Lesley El','Angel Putri','fara ciprit10','Maniac Receh','Alana Basil','EL Frank Ethan','ksupri541@gmail.com','mawar150690@gmail.com','Salsabila','Acek Wew','Kokyu Misariu','Dejon Raon','Joko Sutopo','Barep Pras W',                       'Galuh Prayoga','ramdhan achmad','Aji Saputra Ramadan','Hendra','Dany Catur','EJ','Setya Rangga','Arief Poenya','Ardy LoveHeaven Nabilla','Adi Samsul','Clay Dark','egi pangestu','凡Ɗιs ANDEZ','RANGGEN I-on','joni joni',
'Ahmad Syarifudin','Anime Indo','Vipsaw','Heels Ru','Mardha Waty','andi arjuna','GAREL Hent.','Tian Sopyan','Yanuar Fernandez','Afin Bachtiar','Minu Suherman','King Bug','Dwi Putra','BAHNDITE','Gelas Akua','Febri Hamunangan','Dhanka Maaikha','maru dressden','miftakhul arif','Rahmat Julianto','prayoga galuh','Alfian Tamran',
'Berog Gan','sa ngak','samplokndasmu4@gmail.com','barep praset','Gillang Ellyntina','afara har','Gilang 973','Zackriyya Wong','Curang DROID','Ardy Van Houten','Ahmad Fallz','Mario Teguh','TERBIT SANG SURYA','Dede Mukhtar','Adhy Samsul',
'Rodenmaa R','Jajang Asmara','love Bitcoin','Dhiksa Iswara','song wai','Manuk Piit','Ano Nimus','Khaira Sahid','My Son','shinigami','Ogita Rumansyah','AS Gaming','Aiko Kenangan','Fata Habiburrohman','Adeel Chand',
'LEN. ID','All Game Online27','ffdin dpn','Dani Donk1','Aiola Leo','gear second','alvaro putra','Syamsul Amir','Angela Maras','Dhe Puttri','masasep hasa','Yaah Saaa','Little Night','Fauzistiawan Putra Negerikubang','Arif',
'fara ciprit01','Nicholas Parasian Tampubolon','Rhavael Sumilat','Suko Pauris','Nicholas Parasian Tampubolon','Joko Tingkir','Adi Loro','Angela Maras','Random ChannelTM','GM Kardus','Lukman Hakim','Rival Acc','Warda Tunnisa','Mawar Duri',
'Aditya Abimanyu','Angel Tiara Putri','Aa herry','Ibnu prasetya','xARMY BORNEO','Dimas Budi','Yusdi Albayck','Dani Rpr','banana travel','Nevandra Hensa','Harry 187','Muhamad Fahrul',
'Iriel Tivang','Reza hasad','Derio Geko','Jono Jini','Fashul Id','Foto Rofika','Ryanta','info hits','Rahmat Wiratmoko','Cewek Bohay','muhamad fahrul','Ucok Lele','Billi Almukaromah','Tito Zhafiratul Atmasinta','Nelomo Pubome','Pejelo Vame','manyuabi','Ariipo Vika','Kolt Sunosu','Ghazy',
'Black Smith','mohamad iqbal','Rap- MCT','Tito Zhafiratul Atmasinta','MH Fahrul','ipoel adm','Pendi Doang','eko putra','Abiutomoaji Nawiro',
'Mertua Muda','Abi Utomo Aji','Abi Rizki','Astar','TappeiMix','Iwan Etet','Rois Hasan','irfan hartanto','Ilham','Erik Rizal','Amir Mboyz','Iwanz Chriztchrouw Seven','Sheena callysta almira','Firman Nugraha','MaiBie 1217','dollar india','Never Late','Rolong','Ariek Sundari','Htin Ka Ya M','Santa Santo','Mariano Arias D\'Ygnoti','Dian Cok','lucas.cobosss@gmail.com','angry picnic','Joseph Lee','Pedjuang Dollar','Miftakhul Rizal','curut sengur','galih kurniawan','Paijo Sutrisno',
'Pencari Receh','Rudy Mr13','Octa Core','Dody
','Stree Crew','Awan Hitam','dollar singapura','wjlo234567@gmail.com','ST MBc I','Harris Sopiy','Andy Lay','sadig guna','arjuna 18','Aplikasi Dolar','legitpaypal2@gmail.com','Aqhue Amph Machal','Supriyatna','Miftakhul Rizal','Toto Isytaru','Sam Ping','Claudio Faria','sia cupu','arif fx','Ivan Rakitic','Natalia Angg','Nizar ','Muhammad Nizar','Dhehwhsbdbbdbebebe Bdbdbdjeiejdbfbdb','Siti Farida','Ferdo Danang5','Sella Ayu','Dewa 12','muhammad riza','Sanjaya DxS','zay depraxis','Handika Saputra','asnan asnan','Wardatunnisa','Ayiep Pio','Dewa Dewa','Thoyyib Jiddan','Dika Hardiansyah','AD REVIEW','Dewa Rian','Fahri ardian','hilalmaulana734@gmail.com','Abdu Fajar','Junaidi :v','Kurnia Sandi','Muhammad Fahri Ardiansyah','Trauma Trauma','Sella Ayu Nurmasita','Rizqi Aulia Wildan','James Arthur','Muhammad Fahri Ardiansyah',
'Phytagoras','Rei Morgan','Demittegal 8001','Abdhu Fadjar','raferire2@gmail.com','Max xia Otnong2','LC','kaptenibnu suryajana','Erwin Ardi Zona','Gabriel Roberto','ANGGI','mobilekulegends@gmail.com','deepu t d','Toney','Muspik Amarullah','Roki _07','Dhan Maikha','Bsbsjwiwhebdb Bsbsjsjwjejeb','Erlan Indodax','Adi Bayu','Kenzikenzo','Hendry David','Muspik Amarullah','Nekanata Sumilat','Max xia Otno','sego kucing','gtrekt','adji bae5','Anon Crypt','Chaprid Chan','hendry david','YT BUDI','Fida chanel','Toni','irfan ramadan','Cicak Ruwo','Deepu das T d','Akun Coinbase','ARIF SUPRIYANTO','Fanny Baboond','ahmad syarif','fendyusuf24','Adde Paypal','samsul bachrie','Achjan Amriliyan','Angga Kusumah','Tyo Koro','King Kong','Siti Aisah','Hendra Hamdan','Zahra Adn','Hery Cooprations','Yan Sup','siand','Rizal Lihawa','Jamaludin','r.hermawan1996@gmail.com','clash with mr-x','Akun Mlegends','Buah Hati','Muhammad Opang','novita glaydis anggraini','shit post',
'SB threetwnty','Ahmad Subejo','Yogi Aditia','Arya Putra','StaabWolfPack Gaming','Yohan Troope','Syed Moiz Uddin Ahmed','Dian Safitri','Mbote Ed','Toman Dini','ki palm','Irwan','Shuyaa Goenji','Orang Goblogs','arie putraa','Kang Cury','Furqon','Zuhair Hudry','aden juna','Arsa Rahman','Seaknight12 13','latif ferbri','MYMUSIC sdk','Rizqy Fajar','Yafi\'ah 0611','God Hand','Achmad Mafazun','Rama Dhani','GINA AULIA GG','qais cjdw','DhEni Wahyu ShEtiawan','Nur Cahyo','Rangga Winata','Amier Nahl',
'IndoTUBE','Reza Mustofa','Muhammad Opang','Sapi Junior','Deni Oget','Yogi Aditia','ahmad syarif','Sabar Saja','ryan yunantio','Ika Nasution','Uciha Ainn','Hafidh Artala','Shelley Can','uwitdodo404@gmail.com','Masrani Dewi','cyunix 13','Ricko Setyaw','Reggy Lihawa','Wahid Rivaldy','rozaktuyul0036@gmail.com','Dudoh Tewel','Hery sutiyana','Rizal Al Var','Moeha Moeha','riza wae','Tuyul 243',
'reza abdulrahman','Akun Youtube','Azka Darmawan','Victor Jonas','Rendel Ndel','sgx kaito','Cnazta','RamdaNi YT','BOJES GAMING','Akrom Gamers','Warna Sari','mazeland1901@gmail.com','sukasenang #17',
'Aziz Khadarismawan','Berbagi Ilmu','Satrio Wibowo','Amiek Earn','Rendi Alfiansyah','glaydis','ojan jan','erosensei45@gmail.com','Capcin Sampay','Sentoso','david febri','koko Meo','Mbah 911','dikipernandi saputra','Pongpisut Suayroop','Fadlan Mubarok','Rozak Nuyul',
'pandy almuklas','Iyan Cakrawala','Cnazta Aquariuz','Ecko Budi','Alby Praditya','Fariz Zandi','Purwa Nugraha','Nanang Wijaya','Moch dedy Setiyawan','NFA FAIZ','Kwarasan Knp','Ahmad Subejo','L39248',
'Ihsan Shiddiq','Sinta Bunga','Ihsan Shiddiq','  ꧾꧾ','Eli Rudiyanto','Hacker Ganden','Receh Licorice','Gabriel Swgs','Giant Gaming','Indri Yani','Pesan Singkat','Dani Donk','ArIk Akhir Februari','Dodi Haryanto','Anggi Immah','Bintang Rafl',
'Sinta Bunga','Ihsan Shiddiq','Kurniawan Arief','Rifky Chandra','Ifan Ikshan','Slamet Widodo','Ninja 00','ahmad muharom','Putri Amelia','Simala Kama','Budi Sake','hery cebe independen','Denz Ahmad N','Diky Cahyadi','Denauval Storm','C4RY MORE','King Kong','Dimas Agus','Heldi Arisandi','Nur Syahida','Ferdinan Gagal Kece','iklandoang@gmail.com','Gani Zahidan','Kwarasan Knp','Berasku Sp','Nanto Darta','Moch Dedy Setiyawan','Firdan Alfarizi','Y54166',
 'Indah Channel','PRAKA SAJA','raisaserbasalah4@gmail.com','Mauludin Ihs','Win Arti','Eyik Tama','luffysan2810@gmail.com','Rahman Alle','Doni Pradajaya','Satria Rachmat','Imato Haruki','luffysan2810@gmail.com','Khairul Anas','Muhammad Halqi Adianto','Ahmad AMS','Deri Sableng','bot coin','lisa bonnet','Muh Ainur Ridho','Anang Gamers','Ferdi Chandra','Hanny Dwiyanto','Masha Mawa','elcha 3108','Rinidi Rindi','Muhammad Zainul Asy\'arie','Coffe Maker','Ferdi Chandr',
'Yudis Tira','Rifki Zaenudin','Han Han Sabana Efendi','Mr Avul','AGCteam','Wahyu Ilham','maharani bella','Mas Gl','Dwi Sari','ahmadboncel23@gmail.com','Muh Sayuti','Imazuki Masamuneユースフ','Salik Ambari','Mizan Bagustian','Arfan Stmikh','Dicky Ferdia','Muh Sayuti','Dimas Amar Ma\'ruf','Cintra Kitana','ahmad hamdy','Muhamad Rendi Ekni','Ferdi Chandra','Lukman Lukman','Distantzsw fefdsf','save Akun','Coffe Maker','Tuyul Satu','targetnikah2425@gmail.com','elizabet garden','targetnikahk','Miko Gaming','Cavin Valent','Akbar M S','Yanuar Adri','Cavin Valentino','Diky Ahay','cavin valentino','Supri Yantono','Jancoeg Gaming','Adam Alsavin','donny irawan','van sn','Mizan Tian','Dicky Ferdian','Johan Zarco','Romy Awaked','Lukman Lukman','Isnanik Ernawati','Riski Yorlanda','muhammad kha','abdiel androl','Desan Widodo','targetnikahanku251@gmail.com','A\'an','Ciezs Mill','Nandha Sapoetra','nuyul aplikasii','MENCARI DOLAR','Jibrael Basjir',
 'Rei Morgan','Kukuh Cikal Yuntama','jiezant zuz','Eka Yudha Dhitira','Muh. Risa','Sandi Haris','Syaiful Kempul','elisa driani','Ibrahim Djafar','muhamadsudirna74@gmail.com','Muhammad Rizky','targetnikahku2@gmail.com','xxnextonxx','Gunung Jimat','Athar Rizky','Op0 opo','eko gendon','Cim Ek','bhs btc','Ahmedhamdy','Muzilatullutfi Khakim Sarana','mrrudal74@gm','Aldo Ramadhan','Silvania','Bintang Rafli','Polarinside','Diky Ahay','cavin valent','042gapu@gmail.com','Dwi Nur Riyadi','shev najat','Defacker','nuyul aplikasi','Rayhan CRAFT','31Oc','Johnlenmuel Dacanay','Pasha Maul','Sukmana Dwi Lestari','Aldhy_ Kheci','Roy Roni','Yumna Amelia','tengku vino','ads crooot','kupluk ngantang','Irfan Pay','Irfan Ws','bang jon','Irfan Xns','Irfan Admob','Irfan Ml','irfan warspears','Irfan gaming','Kickdevis Nolimit','King Stillios','Maicol Chavez','Banthink Tv','Bams UF','In Money','Erizal','Opal','dartok dartok','محمد مشهور الهادي','Dav Gamer','Muhamad Fauzi','Elfrisdath Fauzie',
'Dam Walker','Dayat Jati','lightfury1212@gmail.com','Anggi Immah','imam agung','Naira Assafa','Komarudin Komarudin','Echo la Nyo','Zackriyya Wo','Kimkim volg','Saptani 48','Rizaldi Alfian Nur','Andromax V001','central celebes (chanel)','Ale Casselo','Putra Efendi',
'Ichoel','Ayun Abay','Vega Dua','Habib Kasbon','Fiqi Putra','Agus Aan Nur Fauzi','Denauval Darkside','Add Xd','Putra Efendi','Aditya Putra','AFK PLAYER','el diablo','Yocky Andrea','rafzyx12k@gmail.com','DuniaCrypto Mscreator','Paskal Baelon','IRWAN NURYANA','Ardi Setiawan','Alif Ar','Calon Mahasiswa','Patra Comuni','Adi Mas Aji','Marzuki Panjaitan','Neng Udoh','q-wo bae','LILUNG PROJECT','Dewa Firdaus A','Rizky Wahyu','Khoirul Imam1','Adi Mas Aji','Izeco Aori','Toby Hidalgo','Ghosilsilac 78','P22063','Lukman lukma',
'vegazr249@gmail.com','Putra Efendi','Fandia Ananda','Rizaldian','SEKADI KUK','Fitra Dwi','Sri Rahayu','Klik Suro','Muhamad Rizky','Endjii Ghendjii a/ Den_','Muhamad Alfi','Akungameking 01','Gidas Yul','Adi Mas Aji','Diki5 4','Belajar Usaha','Renza Syahputra','Clasic 1985','Tutor PKBM Mitra Mandiri','Reva Bulan','Aluh Kitty','kuramafamilli1@gmail.com','Bernadus Antok','noah84889@gmail.com','Rudy Q Rastafara','Vendi Pendot','Eng Suhendi','Rinaldy 91','andi','TIGA M','Abang Deni','CR Xd16','Rudy Rosemary','Rangga Indra','Musikpedia Ch','TNx Gaming','Tunnix Gaming','Nestor Reyes','Suhendi','fadhil setiono','Arfan Miyaz','Asap Arya','Mafaza','Dvlop -','Sweet Sound','Dede Zaqy','Aldires Raga','r9 tech','Charles Les','fadil atho','heri iswanto','Brilian Putri','yogi ismail','text text','kopi luawak','habib Yushin','Ridwan Bobs','Umar Dony','Kimak Gaming','Big Deep Deep','Dimas Budi7','Ilham Setiawan','Bayangan Semu','Anime Funny','Arlog Benem','giL Project','Ahmad Ardan','jo alex','Eko Ys Real','Ruli Gandari','Memet','Rudy Q Rastafara','Resa Yulia Andini','Rafly Akmal','Garena Bngst','ROMI_16','Ar Rohim','Ridwan Ar','alvin genn',
'Iqbal Hekmatyar','Safz Zher2','Hafidz','Ahmad Alif','Faizal Bahri','chupu grunge','Imam Supryadi','naufalsuryalaga','Alvinn Gennesuuu','SunguT GaminG','PASSIVE CRYPTO EARNINGS','Baby Grunge','FREE ELO','Haikal Afredo','Safitra Mela','Kepo Lele','Kang Arul','ahmad redho','Mbonol','Sisi Gelapku','Kang Bahar','Setan Setan','angga','Taps Praja','LeSotoLe','Hengki Juniarta','mike xza','nabila','Putri Bela','Husni Alexse','Aldy Debores','Saeful Bachri','Walid Kr','Reza Anazz','Ikko Mulyono','alexander dio','Alberto M.M','Aditya Bagaskara','Ilham Setya','DMS 004','Anas Museng','Ling Chui Su','ken matsuyama','jokerinaja007@gmail.com','Fajar Imansyah','gop oop','Mila Dalimunthe','sexy','Achmad FalahulSani','Zon One','marina laucher','PUBG MOMENT','jepot haha','Yusuf Lucky','Matius Aleng','Revina Dea Anggraini','Alip Dansu','Tutor Man','NxFayer Deep','Siro Judin','Anshory Hafiz','irfan hartan',
'rizaalb rizaalb','gian fiuzzu','Gian Dbp','Fairly 912','Dall Booh','Abdur Rosyid','Dönï Bæk','Max wolo','Abie Perdana','n j','ryuaje@gmail.com','Ridho Wahyudi','Egi Pangestu','Rezza Ramadhan','Muhammad Zidane','Muhammad Zidan','Firman Firma','pemburuh dolar 1','Kristina Aulia','Syed Rizal','collingheat23@gmail.com','Leader Orbion','Lubiis Fens','Riza Al B','IDzay Treyana','Adinda Untukmu','Ropek Andres','Mufida Imo','A Mujaki Jak','Fariz Saja','Melik','Yosi Mory','erlangga mfe','Hakimi Yusoff','Rosyid El Ma','Jhon Kinoy','alam bahaya','dimas argara','Dimdim Bae','Diemdiem Bae','abbasydimas@gmail.com','IlhamFitriansyah','Mujas Sjaroh','pakpoh','AG2','RH CHANNEL','agil gatot','Sarijadi_183 SAR','Ripai ','Nizar Miftahul','pemburuh dolar','pemburuh dolar 3','pemburuh.dolarempat@gmail.com','Pemburuh Dolar 5','Zell Corp','Cahyono Cahyono','Fox Razer','enoo rzky','Rainmaker','Sugar Devile','Sulton Mufasit','Benjamin Engel','ALDIEST AJA','route map','Gun Gun','jack.lov.com@gmail.com','ajudantuyul1','Lilung','Joyo Leluhur','Mas Bey Gaming','Alan','Ikiarka Arka','Khaila Bilqis','Bluk','Rajiv Abudzar','VoicesIn MyHeart','Galut Gaming','High Tech All','Yunita','Wahyu Aulia','Nicko Laudrup','Isti Kinarsih','indra','Ghofur Luizz','Prima Angga Wahyu Setiawan','Mas Ariel','calon youtuber rusak','giggs viking','Nuyul Paten2','Kata Siapa','Polos Saja','Reza William',
'Tamvan 354','bagus Abdulr','subroto su','Prima Angga','Zell Corp','sanjayatok8@gmail.com','N3koPoi','miftahull romdhon','samsul bakti','Ndriie Khumaira','abbasyabbasy45@gmail.com','Sarono Kupat','A66175','sanjayatok8@gmail.com','RizkyDharma','Anggi Budi Stiawan','Hasan Ihsan','Mob Ciller','muhammad wendi','Koko Nugroho','Abdul Hadid','Abang ndutz','mas boy','Irham Rifki Mauludi','Ardee Fortes','KRNWN','abu bakrin','Ruli Priyanto','strange world','Iphey bellamy','Jack Jacl','Erwien','Lutfi Cakeoo','Muka Jelek','M Aqim','Yuu ID','iGamingSport 03','Big Match','Hidayat Hidayat','itsMyth 7w7','Yadi Mulyadi','Muhammad Haikal','jonny jonny','Agni Yusuf','berkat.ibu3@gmail.com','Takiya Genji','Jonny','Ardira Sagulasjan','Ferry Purnama','Diky Prastiyo','Zack Zone','Chandu Bhai','Dadang Sukmara','Har Pangestu','Setiawan Iwan','bedull hadid','Danar Yudha','Ahdam Sui','Hamba Allah','kikihasanal28@gmail.com','Renaldi Gunawan','DevanOctavia','Iwan Setyawan','Guts Purwanto','Sixer 56','iman ezie','RizkyTV','vano joker','Adji Nauli','Du Di Dam','Hafiizh Xstream','RiVen P','Acoustic Music','Adi Purnomo','Abdul Hadi','fahmi amirudin','Leha Dhl','bajulandriansya35@gmail.com','salsabilakayla99@gmail.com','Jhon Lail','Jhon Lail','Rizky Receh','Muhamad Rizal','aminkurnia23@gmail.com','hoa phan','Abdul Taufiq','Dejan Wow','hoa phan','Sempak Beracun','D Peace','Muhammad Haikal',
'Jeanice','Erwien','F30286','azka zahran','Kurniawan Zaty','Baghas Shaggy','Ryan Maulidi','Ling Lung','Oi','richie setiawan','Qii Assegaf','Arbain Iswadi','Schnee Raizar','Ardian Pradana Kusuma','kapicirit silite','Hunt People','Jaelani Kusu','Simic Apa ajj','m.yaskur.nasir','M.yaskur.nasir','Noel Junior Parale Ritual','indra irawan','Gagukdk','Rohid lawalata','Maning Gaming','Naya Ajah','Nipzee','Nofrizal Pra','Botlop 001','Firdaus Albab','Firdaus','khairil anwar','Jaelani Kusuma','Sandal Jepit','BLii  Nasikin','Takeshi sakazaki','balmer siallagan','Sasaki Yuto','Deniz Cogan','Calvin Jeremy','Jose Icaza','X Venoms','Ari Sukarno','Trang Cute','Eang 26','aqua blue','Mencari Uang','Reva Rukmana','juna','Gaming Hunter','Yudha Bayu Pranata','Mas Dollar','Urfandy Ibrahim','FREE Chanel','Prayoga Ilham Ilham','Ba Jono','GRL-TV','Muhammad Syultan','Irkhas Ambia Lubis','Elull Gumilangg','Dhamar Ariya','Dhamar Ariya','Nani Kure','M.Aprizal Re','Du Di Dam','ivan ganteng','Abdor Rozak','King Of Pirates Luffy','Fery Fadly','muchamad mahardika','Andyad Andy','Ryan','Дюк Дядюк','Alfredo Mulkay','Hacker illuzi',' 　　　　　　　　　　　 　　　　　　 　　　　　 　　　　　　　　　　　 　　　　　　　　　　　　　　　　　　　　　 　　　　 　　　　　　　　　　 　　　　　　　　 　　　 　　　　　　　　　　　　　　　　　　　　　　　　　　　 　　　　　 　　　 ꧾꧾ','Erwin','Jagoan Mauk','Iwan Setyawan','Devie Ambar',
'Fuji C\'cikal BoentThea','Hunt People','Angel De Ville','Carlos Farmi','Ali Beit','Mahardika Crd','OBAY','Hekel Hekelan','Mencari Uang','Lanceenk Pozaank','RIFIAN GIFAR','alfaeror40@gmail.com','Cimenk gaming','Raihan Maulana','Carlos Farmi','ricky pangestu','O.S Wahyudi','Alfin Smile22','Simic Apa ajj','Alfin aardiansah','Asqallani Njynx','Iko Lovecos','MR. CHIA','Lee Young Tay II','Rifian Gifari','Jumrern Khunta','Ocos Net','Rio Ferdian Nugraha','Siti Hanifah','Kholif Julai','bambang eddy sutjahyo','N Prastiyo','bintang tv','Amad Hidayat','John Opand','Sandal Jepit','Adnan ramadan','Wahyu Andria','Joe Padamai','Jhon`s Cannel','Mangatur','Ardy VHT','Ariza Rinzana','Ranger Of death','Shillver RFN','Řícħø Čąsěŷ','ario tri','N Pras','Peanuts Am','Sany Adi','Dadang Sukmara','Channel Offi','Cou Hen','greenzbee92@gmail.com','Andri Ansyah','uzumady DOANG','Azkiya D\'ziyanu Hermanto','Hermanto','Ari Sukarno','Kamen Kamen','marda google','Koko Jojo','Yt Medan Chanel','Rizki Hamizan','sonika om','music cover','Zuxi Yuyu','Cempaka Gaming','Mariam','Panji NaruChigo','Unta Hamo','Edo Bagus Re','Taupik kurrahman','Yoga Mistek','yoga aldyansyah','Bondan Wirawan','Vitran Putri','Beby Cinaa','Fajar Arif','Ki Sentun','Taupikur Rahman','nani- nani','Firman Syah','N81915','X37592',
'wilmark bece','Aprian Rian','Fas. Win','Krisna\'s Pvp','Gacor Gaming','ryan irham','Susi Lawati','Sebastian Gonzalez','Cencurit ChannelTM','wawan bogel','Dienda Apsella','Adahaja Haja','Lemes Sekali','Madafakah Project','Dodi Effendi','Jeff ian lic','Wanipiro111','Muhammad Siril Wafa','Evandell Tor','Hello Siti','Aa Bb','Bang Yoss','maz idrish','B-a\'bank Ïkhsan Saputra','Ahmad Duki','เบรี่ เบส','bang junaidi','Kamp','andysur GAMING','Abdur rohman','Area Populer','Alfan Mubaro','anton firmansyah','timonatanael9@gmail.com','my devRed','Redho Hermawan','chomenks chomenksfals378','Nova','Safrizal Ilong','Revan Gg','Aov Legenda','Ardi Zx1','hanif Fajar','Gagak Kembar','Susi Lawati','Didot njah','Craf','lulun cyber','Kamen Kamen','Ajisaka Berk','Asep Asep','Bank Yanuar','korban freefire','Moto Travel','Renaldi Gunawan','Muhammad Ghalib','GameOver. ID','vivovoo667@gmail.com','untukwatch ilham','Jimmy Bozka','grenk grenk','Juan Henriquez','Red Aurum','Robb Indigo','Androni We','sugeng wahyudi','Kosong Empty','IMARICK 22','KaNKuN 123','grace diana','Julian Edhar','S.O.S TV','hamdi aja','Pemburu Doll','rahmatrizky4572@gmail.com','Gunawan We Lah','adhi triyanta','ziiear zuniear','Kevinz Kurniawan','Rizki Saputra','Ahmad Riki A','Ana Lontong','zero Art','Irma Yanti','Inara Putri','cah edan','ᴀʏᴀᴍ ɢᴀᴍɪɴɢ','Achmad Taopi','Dede Jumiarto','Aip Samsul Arif','Dinda Rahmadanisa',
'Princealbert','Risna Taufik','tereza reza','robb indigo','FitraAkbar','Amarullah','Dani Rahman','bima rizki','Radenkoplack','Dani Rahman','Putri Syahdini','Riska Apri','Rizki Saputra','Tomad Ber','Muhammad','RayLL Ribeiiro','Risna Taufik','Nuyul Dong','Ikin Supriatna','Gemah ripah Loji','Sarah Warlin','C17420','Putri Syahdini','Marsha Tod','jaran0917@gmail.com','Radenkoplack','Agus Suryanto','perotz ae','Fasa Bo','Riswa Dana','Ardian Ku','Taufik Andrie','andriemsfc141@gmail.com','muhammad farhan','Kerja Kerja','Bang Jali','Super Ardi','salafiyahabuzairi@gmail.com','semua andiny','wong elek','тнє ѕтяιкєя','Adhi Triyanta','Nuyulx1 02','TAKNYANA','Eiidy aLleins','Masup Nibri','Kamil Qureshi','nurippurnawan11092002@gmail.com','Reza Rebellion Rose','RiFa\'i Ariyanto','trhee','4AFV','Septian Dwi','ANIME 369','Hany ','Hendrik Sulistio','Muhammad Zaelani','Gunawan Revi','Valbert 303','Nabilla NurRabbani','Rizki Febrian','Saini TM','Aki Runtuh™','RiFa\'i Mas F','Fahri San','FrEsHsS Cabrera','Ahmad Maulana','Irfan Ijlal Ramadhan','Ardian Rwt','Dito Palentino','Jrx Ms','Mr.hacked Pro','deni doge','ZERO REYKE','Van Kun','R Setyawan Triwinarso','Hakim Ahmad','Aip Samsul A','kiplonds sequarepants','Super Ardi','Bang Miswar','Dimas Arya','Akun Tigapuluh','asli wong jo','Jhonson Pedi','bang kojotz','Tar','yessy yosep','Tasya Elga S','Kuncoro Aji','Difany Oss','Nyoman Jobla','rayllpresi@gmail.com','raden semar','radensemar04@gmail.com','Vikri Ari Nurfi','Cristofer Dominguez','David kurniawan','Dude HowTo?','Murad Murad','Bindu Ajìth','Septiandp','Didi Kempot','Iwan K','ibenkz zetya','Hardian E.C','dzik rul','Jajang Khan','khansaerni@gmail.com','Muh Nizwar','Luri Muhammad Akbar','Line Jogja Tour','Trhee','Bejok Killer',
'Bayu Satya','cumay','Sri Jaka','Guji Huti','Fdysf Gdybo','taupik','RayLL Ribeir','Cristofer Dominguez','J Δ•HoKaGe•Δ','Vain Fury GTR','Tm SouL kz','Muhammad Ainun Nazibb','Sandi Mukhlasin','Aditya Van Bagheur','wirog sableng',
'Sapar Udin','ivan sabil','Garox Project','Sariday','Bayu Alfa','Via Agatha','Arif Boi','Ikhmal Abdullah','Rahmanda Rangga Pradana','Kuba kuba pl','Indra Hidaya','Irfan Kurniawan','Hanif Hh',
'Kings Zhao','REYN NOEDHA PRATAMA','Mukhlis perdana','Zacky St','deden ahmad nawawi','Bun Cu','iwan balok',
'Zbq Ko','Mohammad Towfiq Hossen','Galaxy','Vannesa Angl','Akbar Gaharu','Rahman Muhamad','Kang Kiez','Ridho Firmansyah','Risky channel','Dani Awalludin','Kristian Bayu','Maria Lopes','gagodoh cau','Ahmad Yusuf','Suriadi Rin','Denis Boy Cl','Juragan Tempe',
'Zbq Mi','Angel Maikon','Jien','Maysa Ingin Bahagiieeaa Sa','Zbq Ko','Koenchoro Adjie','Zbq Ko','Alim Hida',
'Muchammad Muid','Farid Husain','Noedho Pratama','Eka Mahardhi','Pukkong21 1298','addesolikin@gmail.com','Adittya Ae West','Yossy Made','Abi Wiryaw','Bikin Baper - BF','Izzun Bae','Afuan Asyura','Aofar','najmudin','Arif Rahman','Vana Cloud','Muhamad Indra Wisnu','Tesra Buit','Zhe Aurel','Fatimah Azah','Junai Di','Sigit Purnomo','Yudie Baskoro','Totok Sujarw','Chandra Purnama','Sultan rewords','riza ma','nabil gps','Ichwan saputra','CingLuw','Samuel Aryo','Ryan Noel','udin lita','Yosrizal ,','Egha Scarlett','free Time','Rio Dimas Pratama','Bery Putra Pati','Isa Maliki','Fernando Put','Galih S','Dandy Dandy','andik tyas','Mohd Ridhwan','JULIG MARSUD','channel_sptr update','Yogi โยคี','Ivan Zulva','Faisal Maulana','Faisal Maulana','semarmoviefi','Ryan Azhari','Handri Dustira','Jaka Gledek','Fajar Pamungkas','Iis Yulianti','Om Jacx','Andri Suhendra','Bruls Crypto','arry artt','Wahyu Praset','Yuga RX','Van Anderson','Venda Candra','Aryunis 77','Ahmad Maulana','timunkattok@gmail.com',
'Awans','Jaelani Orens','Aneuk Cabak Channel','Memed Aneuk Cabak','heri arif','Keepcalm','Satria Mahardika','Tazrian Dwi Saputra','Putri Dewi','Anang Gotte','Pubg Yhas','Tuyil Online','Zaty 6','Animal Lovers','Hatake Kakashi','Muhammad Fajar','Tam bayonG#27','Kun Aji Songo','Surya Hihereafter','Denny Ined','Verry Adiatma','jok kljik','BWI Gaming','Ibnuu Senaa','RafLi','Datoksek Wirawan','JuLian Tika','sugeng Hari','Awan S','Ryan Art',
'lilis','Gabriela Alaxander',
'Andri Nurfajar','now 9','Marfalah','adeyana','Armn Rmdhn12','Bejo Dweso','Yogi Independen','Frentill 123','Hardware Software','Berbagi Tutorial','Memet','Iif Ariefrohman','Ipman Kirishima I','thanoma arli','Ilham Nadhif','Pick Dath','Putri Andini','Kwarasan Knp','Milytha Pabji','Ridhos Hago','Ridho YK','Milyha Dipa','Fanss Milyha','Anun YK Ina','Adeyana Keren\'z','Jono Fice','Dolar Bitcoin','Riyan Azhari','Mas Paijo New','Super Legit','Rhanu Blambangan',
'Aan','Loncek Gilo','Yoni Q','Online Shop','tuyul admob','Robi','chaplin uyee','pletet aku',
'ovay waelah','Oi','Jay-ar Flore','abdull Chanif','alifjw _17','Dicky Sugara','Lukman Hakim','Muhammad Anggi Sugiri','Wahyudi Hidayat','Sony Jaya','Dedy','roy kiyosi',
'HASIBUAN CHANEL','Bilza G','Gabriel Rodriguez','Muhammad Risyad','kentuq kentuq','Abimanyu Sugara','YouTube Joylyf','LZ Nimers','LZ Nimers','gilang 87','Boboho chanel','Lingga','gon kilua','Hermansyah Slw','Sulton Mufasit','Joko Euy','el javanz','iwanfsc','Lanang Akira','Bisma Bisbahudin','Aziz Cahyo','JustKIM','Sutikno','taicok679@gmail.com','Wahyu Dan Rezi','LZ Nimers',
'Mugshit Haikal','mohan bakti','Lana Prihandoyo','cio_alt69@yahoo.com','Dr. android','Aderian Nopiana','Torrejon Padilla Sebastian Job','Trần Bích Ngọc','Salsabila','ajay lovely','Taufik','mis bohay','Agni Yusuf','Aderian Nopiana','Rangga Saputra','Danial Suaib',
'Aldy dwinop','Dede Dede','ORBITRON CHANNEL','Leadpiar Leadpiar','Anime And Games','Same hesa','Aditya Gaming','Bagas Nur Fa','project M/V','Rasyla RafarDhan',
'krisna pvp','Zouka Tamaqu','QF Money','Krisnapurbak','Doel R',
'anna margaretta','nur zaman','Muhamad Ristiyanto','ANGGA ADITYA','Harvey Gosal','Santoso Ae','Ap Bocaw','Ferry Gunawan','Pakun','Rian 26','pletok sungkono','mas hehe','Munawir CL','Si Putra','akun04032003@gmail.com','Adi 08','AB all buddy','cahyo bhudhy','* Se *','Cahyo Bhudhy','Rozir Wobari','Andik','Danial Suaib','Ware Ares','Dzaki A Rasy','Job Padilla','nada mustafa','Khalisah Syafiqah','Envy Kun','MAriyanto','scalper wartune','Kingdomia Android','Pak Rafi','Ailuz Gamers','Andi Suwandi','Ekir 08','Jack Djokam','pelacurbanget@gmail.com','Guardians Des0','Rony Pubg','Jack Djokam','Merry Loe','salma gondang','かねき','leo julianto',
'Samuel Batara','anna margaretta','nur zaman','Muhamad Ristiyanto','ANGGA ADITYA','Harvey Gosal','Santoso Ae','Ap Bocaw','Ferry Gunawan','Muhammad• Ardi','Super Hero','Agara Net','dede gerang50','Deny Setiyawan','Nasrul Hafiz','Syaiful Hammam','Sandy Lay','Lilung','Osamu Dazai','Jack djokam','Kosasi Djokam','Rama Dani','Sangpemburu 35',
'Dolhan',
'Asri Maulina','Cryptocurrency Info','Wahid Rivaldy','Indra Adiwijaya','Ane Tuy02','Ayu Amalia',
'fir02061995@gmail.com','Wai Phyo','Zein Azka Muhammad','satan lay','ONE FOR ALL ','Regu Garuda','Adderly Hida','gigih gunawa','Muhyi Din','Ariel Steven','muhammad naufal','Nury Waelah','Tusta Gaura Das Tobia','zakaria rama','BamZ Kocak','Bam Z','Saifulbr Z','Sugara',
'ardi purnomo95','Dodi Fares Tersisi',
'salwa aqilah','channel ketonggeng axsis','Ovay Waelah','farel setiawan','Rafi Alaudin','Apriyan FeliCiano','Ade Supriatna',
'Debora','apps and gamer channel','Rizal','komang madri','omosnon69@gm','Mayan Receh','Arfa Nusabariana','ံံံံ ံံံံ','Abdul Hafiz','H48714',
'phreaker AE','Aqiila fitnes Center','Bikin Baper - BF','E92939',
'Didix Sujarno','Nur Mualifah','Soj Charlotte',
'riot\'s btrsd','Darma Chandra','King Kuchand','Eko Supriadi','nindy jeihan','Rizal Nasion','Bang Kins','Aryo Joni','Pertuyulan Gangstar','Reza Dekko',
'rizalnasional1995@gmail.com','Arya Kc','Wahduaenam',
'Reza Ahbani','Windii Rachmat','Hime Daisuki','Kimi Hime',
'Lisin','Sina Jiam','Iyan Out Sider\'s','Flo Renza','Đại Thánh','Lisin','Liheli Prasugi','Da Chan','Fr Swt','Thảo','Wanchat','Jhon Philon Setiawan',
'Domminic Toretto','Desu Stunner','ATri _Ngasso',
'Hellen Park','sota zucchi','Kokyu Misariu','lankkcrew','alex eloco',
'aryo pratama','Ejenk Andreas','Freefire Saya','Abot stand',
'J51452','Muhammad Firmansyah','Kokyu Misariu','lankkcrew','alex eloco','Dickof Zapat','Mai Mai','Dani Kurnian','TEST TERBAIK','  ꧾꧾ','Dickof Zapatista','Tuyul Nuyul',
'rafa sya','Randi Rahmadi',
'nwanda','khamidlillah99@gmail.com','Randhika sayoga Putra firdaus','Aw He','I DK','IndraWan','TWO CRAFTER','Dami Syahputra',
'Sisca Nurmala','Xavier Yo','Indra Adi','Aimach Fawaid','Sayang Selalu','Agara Net',
'Ibnu Wildan','DuM DuM','Alifmaulanaishaq00 7','Tegoeh Pituwolu',
'NURUL IMAMAH','Syafa Mx','jaran0917@gmail.com','Viermantz Chiboedaxslegedtz Nugraha','Black Shark','Muh Roni','Forum Facebook','Ismi Riko',
'Amhs Ayuha','Rizki Fadillah','Fahmi Yea','Ren Gun','Si Cuplish',
'Mercy Benz','fajar','novan fardiansah','My Account','My Account','android cool','android cool','Yohanes Sefrianto','Bang Beib','Abid Nasrulloh','ferry edition','Dhe Va','Sena Hlb','Yusuf Panji','UnyiL Arfy','KRNOOB GAMING','Galuh Pratama','Novan Ferdiansyah','Nova Hermilinda','Bang Acil\'s',
'Wabidin __','Novan Ferdiansah','Zain Plong','Loading','Ibnu Aspar','ocid warhowl','Tuan anh Ngu','erusukami@gmail.com','Ngepet Dollar','Muhammad Imam Hafizh',
'Sepatu Bro','Salvador Jeffrey','Jhetz','Xeon Gt','yoga pratama','DZ Gaming','Muhammad Khatama','Kha Han',
'Muhamad Yoga','Jaenk Rane','Mink Hilman','Qmink Maul','Erlangga Cliquerz','Novianti Angga',
'Fake Music','Fake Music','Datuk Kayo','  Siber','Kwarasan Knp','Ridhos Hago',
'Candu Sang P','Osnon Cobain','Hayi Sofantono','Cnazta Aquariuz','Enchi','Nur Rohman Firdaus','candu kopi','Ejenk Andreas','Muhammad Amin','Egy Fazry','Mercy Benz','Kopet','Dilah Art','Key Z','Budianto Riski','Umam Mayor','Akun Coc','Watch Earn','maulana eka',
'Garena Free fire','Richard Antonio','Ade Karen',
'Syed Naseer','Daniel Argus','Gimenz ID','Tedi Junaedi','  ꧾꧾ',
'NimoLoL YT','Reza K','Masudi','  ꧾꧾ','Tari Wsm','zoe cold','Muammar Mufid','Luwi Yati','X Emperer28',
'achmad Muhammad','Mr Uzzz','Muaela Dewi','Thyaz Februarini','Riyan Adhy','Nanang Sugih','Jefri Wibisono','P.phanwisa','P.phanwisa',

       ];

$toto = ['tes',];
$ydnews = ['tes','adidoank',];
