#!/bin/sh

# Colors
blue='\e[1;34'
cyan='\e[1;36m'
green='\e[1;34m'
okegreen='\033[92m'
lightgreen='\e[1;32m'
white='\e[1;37m'
red='\e[1;31m'
yellow='\e[1;33m'

# Banner
banner(){
    clear
    echo -e ""
    echo -e "$red    フ$yellowァ$greenッ$cyanク$okegreenユ$lightgreenー$white"
    echo -e ""
}

banner
echo -e " ex     : example.com"
read -p " target : " target;
banner
curl https://api.hackertarget.com/zonetransfer/?q=$target
echo -e ""